### ISSUE TITLE
[GALOY] Get websockets to connect successfully in Web Wallet

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/web-wallet#3]
This task is to configure the Web Wallet (or Charts) repo correctly so that the websockets are connecting when starting up the Web Wallet on port 3000.

For testing the frontend you can connect the staging environment to https://development.flashapp.me:8080/graphql
Websocket is currently set up at wss://development.flashapp.me:8080/graphqlws

You can build the web wallet locally and try to connect it to the staging environment to test the websocket connection

BOUNTY available ⚡⚡⚡

This bounty may include changes to the following other repos:

https://github.com/lnflash/charts
https://github.com/lnflash/flash

**Comment by ecurrencyhodler** [comment]
Bounty has been [posted](https://community.sphinx.chat/bounty/548)!

**Comment by islandbitcoin** [comment]
This bounty may include changes to the following other repos:

- https://github.com/lnflash/charts
- https://github.com/lnflash/flash

**Comment by tobi-bams** [comment]
Hi @islandbitcoin  looking into the web socket issue, I guess the web socket URL you are providing is not correct, that’s why it’s failing

You can use this website to test web socket connection: https://www.piesocket.com/websocket-tester

This is the web socket URL I found on the ticket: [wss://development.flashapp.me:8080/graphqlws](http://wss//development.flashapp.me:8080/graphqlws)

**Comment by tobi-bams** [comment]
Also, you can test the Galoy staging web socket on the website above: 
[wss://ws.staging.galoy.io/graphql](http://wss//ws.staging.galoy.io/graphql)

**Comment by islandbitcoin** [comment]
I see that the URL is failing, but how do you know it is not correct?

**Comment by islandbitcoin** [comment]
here is the code snippet where the DEV environment is configured to use that URL

https://github.com/lnflash/flash/blob/f99f6f618f009c91cea6e79c585e80ca3df30e95/dev/ory/oathkeeper_rules.yaml#L37-L49

**Comment by tobi-bams** [comment]
> here is the code snippet where the DEV environment is configured to use that URL
> 
> https://github.com/lnflash/flash/blob/f99f6f618f009c91cea6e79c585e80ca3df30e95/dev/ory/oathkeeper_rules.yaml#L37-L49


Also, I noticed you are using `https` or `http` and not `wss` or `ws` in the config

**Comment by islandbitcoin** [comment]
> > here is the code snippet where the DEV environment is configured to use that URL
> > https://github.com/lnflash/flash/blob/f99f6f618f009c91cea6e79c585e80ca3df30e95/dev/ory/oathkeeper_rules.yaml#L37-L49
> 
> Also, I noticed you are using `https` or `http` and not `wss` or `ws` in the config

This is not my code, this is the original upstream code from galoy, possibly the same code that is running on [wss://ws.staging.galoy.io/graphql](http://wss//ws.staging.galoy.io/graphql)

The bounty is to try and figure out why this fork is not working the same as the galoy code.

You can see all the code changes in the fork for reference here: https://github.com/lnflash/flash/compare/main...lnflash:flash:ibex-integrated

**Comment by tobi-bams** [comment]
@islandbitcoin please is this graphql url still live???: [https://development.flashapp.me:8080/graphql](https://development.flashapp.me:8080/graphql)

I can't access it...

**Comment by islandbitcoin** [comment]
looks like the HTTPS keeps failing, but you can still access it via http on port 4002

**Comment by islandbitcoin** [comment]
I started another port forwarding on port 8080 for HTTPS. Hopefully it stays up

**Comment by tobi-bams** [comment]
> * https://github.com/lnflash/flash

Tried it now, seems its down again

**Comment by tobi-bams** [comment]
Please can you check want you have here on where you are running your server, seems websocket is running on a different port: [.env](https://github.com/lnflash/flash/blob/main/.env#L81)

**Comment by tobi-bams** [comment]
> Please can you check want you have here on where you are running your server, seems websocket is running on a different port: [.env](https://github.com/lnflash/flash/blob/main/.env#L81)

If that's the case, please can you forward the port web socket is running on

**Comment by islandbitcoin** [comment]
I'm back home from traveling now, and port 8080 for HTTPS is up and running.

I'm not sure what you mean by the port the websocket is running on. 
I'm running the entire stack in a k8s container, with an ingress point at 4002(http) and 8080(https)

all services are resolving from the ingress, including the websocket

**Comment by islandbitcoin** [comment]
resolved.
